### ISSUE TITLE
Python 2.x futures library not installed on CentOS 7.5

### ISSUE THREAD

**Issue by xenophonf** [irtnog/certbot-formula#1]
I configured certbot-formula to install the following packages:

  - certbot
  - python2-certbot-dns-route53
  - jq

On an older system, this configuration was able to run the `certbot` command without any difficulty.  However, on a new install of CentOS 7.5 (build 1805), the `certbot` command fails with this error:

```
          ID: certbot_run
    Function: cmd.run
        Name: certbot certonly --non-interactive --keep-until-expiring --renew-with-new-domains --cert-name www.example.com -d www.example.com
      Result: False
     Comment: Command "certbot certonly --non-interactive --keep-until-expiring --renew-with-new-domains --cert-name www.example.com -d www.example.com" run
     Started: 17:02:39.723105
    Duration: 330.373 ms
     Changes:
              ----------
              pid:
                  22289
              retcode:
                  1
              stderr:
                  An unexpected error occurred:
                  DistributionNotFound: futures>=2.2.0,<4.0.0
                  Please see the logfile '/tmp/tmpvcIEbe' for more details.
              stdout:
```

To work around this problem, install the python2-futures package.
